name: CI

on:
  push:
    branches:
      - "*" # Trigger on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.13.1"

      - name: Install dependencies
        run: npm install

      - name: Run tests and build
        run: |
          npm run build
          npm test
        env:
          CI: true

      - name: Deploy to Netlify
        if: success()
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: ./build
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Notify on failure
        if: failure()
        run: echo "Build or tests failed. Check the logs."

      - name: Notify on success
        if: success()
        run: echo "Build and tests passed successfully."